#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800

#define PLAYER_START_POSITION_X 300
#define PLAYER_START_POSITION_Y 400

#define FLOOR_HEIGHT 180

#define MAX_PIPE_COUNT 7
#define LAST_PIPE MAX_PIPE_COUNT - 1

#endif /* CONSTANTS_H */
